### ISSUE TITLE
Tag association conflicts with actionpack's tag_helper when running rake tasks

### ISSUE THREAD

**Issue by Hatlen** [thoughtbot/factory_girl_rails#191]
I have a factory like this

```ruby
factory :tag do
  name "asdf"
end

factory :something_with_tag do
  name "asdf"  
  tag
end
```

And when I try to run a task: `RAILS_ENV bundle exec rake db:schema:load` 
I get an exception, that the tag function (actionpack's tag_helper) is called with to few arguments.
If you want some more info I'll gladly fix that.

If I run it with --trace this is the output:

```
~/Projects/the-project> RAILS_ENV=test be rake db:schema:load --trace
** Invoke db:schema:load (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
ArgumentError: wrong number of arguments (0 for 1..4)
/Users/Trond/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-3.2.22.1/lib/action_view/helpers/tag_helper.rb:65:in `tag'
/Users/Trond/Projects/the-project/spec/factories.rb:545:in `block (2 levels) in <top (required)>'
/Users/Trond/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/factory_girl-3.3.0/lib/factory_girl/syntax/default.rb:18:in `instance_eval'
/Users/Trond/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/factory_girl-3.3.0/lib/factory_girl/syntax/default.rb:18:in `factory'
/Users/Trond/Projects/the-project/spec/factories.rb:544:in `block in <top (required)>'
/Users/Trond/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/factory_girl-3.3.0/lib/factory_girl/syntax/default.rb:49:in `instance_eval'
/Users/Trond/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/factory_girl-3.3.0/lib/factory_girl/syntax/default.rb:49:in `run'
/Users/Trond/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/factory_girl-3.3.0/lib/factory_girl/syntax/default.rb:7:in `define'
/Users/Trond/Projects/the-project/spec/factories.rb:2:in `<top (required)>'
/Users/Trond/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-3.2.22.1/lib/active_support/dependencies.rb:245:in `load'
/Users/Trond/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-3.2.22.1/lib/active_support/dependencies.rb:245:in `block in load'
/Users/Trond/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-3.2.22.1/lib/active_support/dependencies.rb:236:in `load_dependency'
/Users/Trond/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-3.2.22.1/lib/active_support/dependencies.rb:245:in `load'
/Users/Trond/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/factory_girl-3.3.0/lib/factory_girl/find_definitions.rb:16:in `block in find_definitions'
/Users/Trond/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/factory_girl-3.3.0/lib/factory_girl/find_definitions.rb:15:in `each'
/Users/Trond/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/factory_girl-3.3.0/lib/factory_girl/find_definitions.rb:15:in `find_definitions'
/Users/Trond/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/factory_girl_rails-3.3.0/lib/factory_girl_rails/railtie.rb:26:in `block in <class:Railtie>'
/Users/Trond/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-3.2.22.1/lib/active_support/lazy_load_hooks.rb:34:in `call'
/Users/Trond/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-3.2.22.1/lib/active_support/lazy_load_hooks.rb:34:in `execute_hook'
/Users/Trond/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-3.2.22.1/lib/active_support/lazy_load_hooks.rb:43:in `block in run_load_hooks'
/Users/Trond/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-3.2.22.1/lib/active_support/lazy_load_hooks.rb:42:in `each'
/Users/Trond/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-3.2.22.1/lib/active_support/lazy_load_hooks.rb:42:in `run_load_hooks'
/Users/Trond/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-3.2.22.1/lib/rails/application/finisher.rb:59:in `block in <module:Finisher>'
/Users/Trond/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-3.2.22.1/lib/rails/initializable.rb:30:in `instance_exec'
/Users/Trond/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-3.2.22.1/lib/rails/initializable.rb:30:in `run'
/Users/Trond/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-3.2.22.1/lib/rails/initializable.rb:55:in `block in run_initializers'
/Users/Trond/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-3.2.22.1/lib/rails/initializable.rb:54:in `each'
/Users/Trond/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-3.2.22.1/lib/rails/initializable.rb:54:in `run_initializers'
/Users/Trond/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-3.2.22.1/lib/rails/application.rb:136:in `initialize!'
/Users/Trond/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-3.2.22.1/lib/rails/railtie/configurable.rb:30:in `method_missing'
/Users/Trond/Projects/the-project/config/environment.rb:6:in `<top (required)>'
/Users/Trond/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-3.2.22.1/lib/active_support/dependencies.rb:251:in `require'
/Users/Trond/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-3.2.22.1/lib/active_support/dependencies.rb:251:in `block in require'
/Users/Trond/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-3.2.22.1/lib/active_support/dependencies.rb:236:in `load_dependency'
/Users/Trond/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-3.2.22.1/lib/active_support/dependencies.rb:251:in `require'
/Users/Trond/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-3.2.22.1/lib/rails/application.rb:103:in `require_environment!'
/Users/Trond/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-3.2.22.1/lib/rails/application.rb:305:in `block (2 levels) in initialize_tasks'
/Users/Trond/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `call'
/Users/Trond/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute'
/Users/Trond/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `each'
/Users/Trond/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'
/Users/Trond/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/Users/Trond/.rbenv/versions/2.2.3/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/Users/Trond/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Users/Trond/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:201:in `block in invoke_prerequisites'
/Users/Trond/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:199:in `each'
/Users/Trond/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:199:in `invoke_prerequisites'
/Users/Trond/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
/Users/Trond/.rbenv/versions/2.2.3/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/Users/Trond/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Users/Trond/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'
/Users/Trond/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:150:in `invoke_task'
/Users/Trond/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/Users/Trond/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `each'
/Users/Trond/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block in top_level'
/Users/Trond/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:115:in `run_with_threads'
/Users/Trond/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:100:in `top_level'
/Users/Trond/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:78:in `block in run'
/Users/Trond/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/Users/Trond/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
/Users/Trond/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/bin/rake:33:in `<top (required)>'
/Users/Trond/.rbenv/versions/2.2.3/bin/rake:23:in `load'
/Users/Trond/.rbenv/versions/2.2.3/bin/rake:23:in `<main>'
Tasks: TOP => db:schema:load => environment

```

Thanks!

**Comment by Hatlen** [comment]
I think I was to fast :)
