### ISSUE TITLE
Gem Load Error is: undefined method `blank?' for class `FactoryGirl::DefinitionProxy'

### ISSUE THREAD

**Issue by evenluo** [thoughtbot/factory_girl_rails#215]
It worked just fine until today. This error came out nowhere, because I did't do anything about it at all. And I didn't call `blank?` method in my whole project. So what's happening. Thank you very much.

```
Gem Load Error is: undefined method `blank?' for class `FactoryGirl::DefinitionProxy'
Backtrace for gem load error is:
/Users/evenluo/.rvm/gems/ruby-2.3.1/gems/factory_girl-4.7.0/lib/factory_girl/definition_proxy.rb:6:in `undef_method'
/Users/evenluo/.rvm/gems/ruby-2.3.1/gems/factory_girl-4.7.0/lib/factory_girl/definition_proxy.rb:6:in `block in <class:DefinitionProxy>'
/Users/evenluo/.rvm/gems/ruby-2.3.1/gems/factory_girl-4.7.0/lib/factory_girl/definition_proxy.rb:5:in `each'
/Users/evenluo/.rvm/gems/ruby-2.3.1/gems/factory_girl-4.7.0/lib/factory_girl/definition_proxy.rb:5:in `<class:DefinitionProxy>'
/Users/evenluo/.rvm/gems/ruby-2.3.1/gems/factory_girl-4.7.0/lib/factory_girl/definition_proxy.rb:2:in `<module:FactoryGirl>'
/Users/evenluo/.rvm/gems/ruby-2.3.1/gems/factory_girl-4.7.0/lib/factory_girl/definition_proxy.rb:1:in `<top (required)>'
/Users/evenluo/.rvm/gems/ruby-2.3.1/gems/factory_girl-4.7.0/lib/factory_girl.rb:35:in `require'
/Users/evenluo/.rvm/gems/ruby-2.3.1/gems/factory_girl-4.7.0/lib/factory_girl.rb:35:in `<top (required)>'
/Users/evenluo/.rvm/gems/ruby-2.3.1/gems/factory_girl_rails-4.7.0/lib/factory_girl_rails/railtie.rb:1:in `require'
/Users/evenluo/.rvm/gems/ruby-2.3.1/gems/factory_girl_rails-4.7.0/lib/factory_girl_rails/railtie.rb:1:in `<top (required)>'
/Users/evenluo/.rvm/gems/ruby-2.3.1/gems/factory_girl_rails-4.7.0/lib/factory_girl_rails.rb:1:in `require'
/Users/evenluo/.rvm/gems/ruby-2.3.1/gems/factory_girl_rails-4.7.0/lib/factory_girl_rails.rb:1:in `<top (required)>'
/Users/evenluo/.rvm/gems/ruby-2.3.1/gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `require'
/Users/evenluo/.rvm/gems/ruby-2.3.1/gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `block (2 levels) in require'
/Users/evenluo/.rvm/gems/ruby-2.3.1/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `each'
/Users/evenluo/.rvm/gems/ruby-2.3.1/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `block in require'
/Users/evenluo/.rvm/gems/ruby-2.3.1/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `each'
/Users/evenluo/.rvm/gems/ruby-2.3.1/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `require'
/Users/evenluo/.rvm/gems/ruby-2.3.1/gems/bundler-1.12.5/lib/bundler.rb:102:in `require'
/Users/evenluo/Develop/LinkFirms/Bourne/config/application.rb:7:in `<top (required)>'
/Users/evenluo/Develop/LinkFirms/Bourne/config/environment.rb:2:in `require_relative'
/Users/evenluo/Develop/LinkFirms/Bourne/config/environment.rb:2:in `<top (required)>'
/Users/evenluo/Develop/LinkFirms/Bourne/spec/rails_helper.rb:3:in `require'
/Users/evenluo/Develop/LinkFirms/Bourne/spec/rails_helper.rb:3:in `<top (required)>'
/Users/evenluo/Develop/LinkFirms/Bourne/spec/controllers/api/v1/base_controller_spec.rb:1:in `require'
/Users/evenluo/Develop/LinkFirms/Bourne/spec/controllers/api/v1/base_controller_spec.rb:1:in `<top (required)>'
/Users/evenluo/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.1/lib/rspec/core/configuration.rb:1435:in `load'
/Users/evenluo/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.1/lib/rspec/core/configuration.rb:1435:in `block in load_spec_files'
/Users/evenluo/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.1/lib/rspec/core/configuration.rb:1433:in `each'
/Users/evenluo/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.1/lib/rspec/core/configuration.rb:1433:in `load_spec_files'
/Users/evenluo/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.1/lib/rspec/core/runner.rb:100:in `setup'
/Users/evenluo/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.1/lib/rspec/core/runner.rb:86:in `run'
/Users/evenluo/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.1/lib/rspec/core/runner.rb:71:in `run'
/Users/evenluo/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.1/lib/rspec/core/runner.rb:45:in `invoke'
/Users/evenluo/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.1/exe/rspec:4:in `<top (required)>'
/Users/evenluo/.rvm/gems/ruby-2.3.1/bin/rspec:23:in `load'
/Users/evenluo/.rvm/gems/ruby-2.3.1/bin/rspec:23:in `<main>'
/Users/evenluo/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/Users/evenluo/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by evenluo** [comment]
I figure it out. It's the gem I add recently. It cause this error

**Comment by schwinnn** [comment]
Did you find the reason?

**Comment by schwinnn** [comment]
@evenluo

**Comment by evenluo** [comment]
@schwinnn Did you add any new gems in your project recently? For me , It's the jpush gem
