### ISSUE TITLE
Validation error while there is no validation in Model

### ISSUE THREAD

**Issue by asad-ali-bhatti** [thoughtbot/factory_girl_rails#227]
I am trying to create a factory but it gives me annoying error 

**my model:**
class Storage < ApplicationRecord
  has_many   :child_storages, foreign_key: :parent_storage_id, class_name: 'Storage'
  belongs_to :parent_storage, class_name: 'Storage'
end

**Factory**
FactoryGirl.define do
  factory :storage do
    name Faker::Name.first_name
  end
end

when I try to use it, it gives this error

ActiveRecord::RecordInvalid:
       Validation failed: Parent storage must exist
     # /home/asad/.rvm/gems/ruby-2.3.3@mystorage/gems/factory_girl-4.8.0/lib/factory_girl/configuration.rb:18:in `block in initialize'
     # /home/asad/.rvm/gems/ruby-2.3.3@mystorage/gems/factory_girl-4.8.0/lib/factory_girl/evaluation.rb:15:in `create'
     # /home/asad/.rvm/gems/ruby-2.3.3@mystorage/gems/factory_girl-4.8.0/lib/factory_girl/strategy/create.rb:12:in `block in result'
     # /home/asad/.rvm/gems/ruby-2.3.3@mystorage/gems/factory_girl-4.8.0/lib/factory_girl/strategy/create.rb:9:in `tap'
     # /home/asad/.rvm/gems/ruby-2.3.3@mystorage/gems/factory_girl-4.8.0/lib/factory_girl/strategy/create.rb:9:in `result'
     # /home/asad/.rvm/gems/ruby-2.3.3@mystorage/gems/factory_girl-4.8.0/lib/factory_girl/factory.rb:42:in `run'
     # /home/asad/.rvm/gems/ruby-2.3.3@mystorage/gems/factory_girl-4.8.0/lib/factory_girl/factory_runner.rb:29:in `block in run'
     # /home/asad/.rvm/gems/ruby-2.3.3@mystorage/gems/factory_girl-4.8.0/lib/factory_girl/factory_runner.rb:28:in `run'
     # /home/asad/.rvm/gems/ruby-2.3.3@mystorage/gems/factory_girl-4.8.0/lib/factory_girl/strategy_syntax_method_registrar.rb:20:in `block in define_singular_strategy_method'
     # ./spec/models/storage_spec.rb:17:in `block (2 levels) in <top (required)>'
     # ./spec/models/storage_spec.rb:19:in `block (2 levels) in <top (required)>'

**Comment by tomdracz** [comment]
@asad-ali-bhatti Rails 5 makes belongs_to fail if association is not present. 
See https://til.hashrocket.com/posts/ca64beda59-rails-5-changed-belongsto-default-validation

In your case, you should probably add optional: true to your belongs_to declaration like:

```
class Storage < ApplicationRecord
  has_many   :child_storages, foreign_key: :parent_storage_id, class_name: 'Storage'
  belongs_to :parent_storage, optional: true, class_name: 'Storage'
end

```

**Comment by subelsky** [comment]
This looks like the same issue as #232 - so if you don't set `optional: true` then your factory would have to define a `parent_storage`
