### ISSUE TITLE
NameError: wrong constant name

### ISSUE THREAD

**Issue by Oshuma** [thoughtbot/factory_girl_rails#234]
I'm in the process of upgrading a Rails 3.2 app to Rails 4.2 and I'm running into the exception mentioned in the title.  I've upgraded to the latest (as of this writing) version of factory_girl_rails (`4.8.0`).  Before moving over to Rails 4.2, the specs were passing on Rails 3.2 using factory_girl_rails version `3.4.0`.  I can provide more info if needed.

```
  54) User#can_flag_listing? 
      Failure/Error: let!(:listing_2) { FactoryGirl.create(:listing) }
      
      NameError:
        wrong constant name 
      # /opt/circleci/.rvm/gems/ruby-2.1.8/gems/activesupport-4.2.8/lib/active_support/inflector/methods.rb:254:in `const_get'
      # /opt/circleci/.rvm/gems/ruby-2.1.8/gems/activesupport-4.2.8/lib/active_support/inflector/methods.rb:254:in `constantize'
      # /opt/circleci/.rvm/gems/ruby-2.1.8/gems/activesupport-4.2.8/lib/active_support/core_ext/module/introspection.rb:31:in `parent'
      # /opt/circleci/.rvm/gems/ruby-2.1.8/gems/activerecord-4.2.8/lib/active_record/model_schema.rb:322:in `compute_table_name'
      # /opt/circleci/.rvm/gems/ruby-2.1.8/gems/activerecord-4.2.8/lib/active_record/model_schema.rb:165:in `reset_table_name'
      # /opt/circleci/.rvm/gems/ruby-2.1.8/gems/activerecord-4.2.8/lib/active_record/model_schema.rb:126:in `table_name'
      # /opt/circleci/.rvm/gems/ruby-2.1.8/gems/activerecord-4.2.8/lib/active_record/model_schema.rb:230:in `table_exists?'
      # /opt/circleci/.rvm/gems/ruby-2.1.8/gems/activerecord-4.2.8/lib/active_record/attribute_methods/primary_key.rb:97:in `get_primary_key'
      # /opt/circleci/.rvm/gems/ruby-2.1.8/gems/activerecord-4.2.8/lib/active_record/attribute_methods/primary_key.rb:85:in `reset_primary_key'
      # /opt/circleci/.rvm/gems/ruby-2.1.8/gems/activerecord-4.2.8/lib/active_record/attribute_methods/primary_key.rb:73:in `primary_key'
      # /opt/circleci/.rvm/gems/ruby-2.1.8/gems/protected_attributes-1.1.3/lib/active_record/mass_assignment_security/attribute_assignment.rb:15:in `attributes_protected_by_default'
      # /opt/circleci/.rvm/gems/ruby-2.1.8/gems/protected_attributes-1.1.3/lib/active_model/mass_assignment_security.rb:337:in `block in protected_attributes_configs'
      # /opt/circleci/.rvm/gems/ruby-2.1.8/gems/protected_attributes-1.1.3/lib/active_record/mass_assignment_security/inheritance.rb:13:in `yield'
      # /opt/circleci/.rvm/gems/ruby-2.1.8/gems/protected_attributes-1.1.3/lib/active_record/mass_assignment_security/inheritance.rb:13:in `subclass_from_attributes?'
      # /opt/circleci/.rvm/gems/ruby-2.1.8/gems/activerecord-4.2.8/lib/active_record/inheritance.rb:54:in `new'
      # /opt/circleci/.rvm/gems/ruby-2.1.8/gems/factory_girl-4.8.0/lib/factory_girl/decorator/new_constructor.rb:9:in `new'
      # /opt/circleci/.rvm/gems/ruby-2.1.8/gems/factory_girl-4.8.0/lib/factory_girl/decorator.rb:14:in `send'
      # /opt/circleci/.rvm/gems/ruby-2.1.8/gems/factory_girl-4.8.0/lib/factory_girl/decorator.rb:10:in `method_missing'
      # /opt/circleci/.rvm/gems/ruby-2.1.8/gems/factory_girl-4.8.0/lib/factory_girl/decorator/invocation_tracker.rb:11:in `method_missing'
      # /opt/circleci/.rvm/gems/ruby-2.1.8/gems/factory_girl-4.8.0/lib/factory_girl/decorator.rb:14:in `send'
      # /opt/circleci/.rvm/gems/ruby-2.1.8/gems/factory_girl-4.8.0/lib/factory_girl/decorator.rb:10:in `method_missing'
      # /opt/circleci/.rvm/gems/ruby-2.1.8/gems/factory_girl-4.8.0/lib/factory_girl/configuration.rb:19:in `block in initialize'
      # /opt/circleci/.rvm/gems/ruby-2.1.8/gems/factory_girl-4.8.0/lib/factory_girl/attribute_assigner.rb:48:in `instance_exec'
      # /opt/circleci/.rvm/gems/ruby-2.1.8/gems/factory_girl-4.8.0/lib/factory_girl/attribute_assigner.rb:48:in `build_class_instance'
      # /opt/circleci/.rvm/gems/ruby-2.1.8/gems/factory_girl-4.8.0/lib/factory_girl/attribute_assigner.rb:13:in `object'
      # /opt/circleci/.rvm/gems/ruby-2.1.8/gems/factory_girl-4.8.0/lib/factory_girl/evaluation.rb:12:in `object'
      # /opt/circleci/.rvm/gems/ruby-2.1.8/gems/factory_girl-4.8.0/lib/factory_girl/strategy/create.rb:9:in `result'
      # /opt/circleci/.rvm/gems/ruby-2.1.8/gems/factory_girl-4.8.0/lib/factory_girl/factory.rb:42:in `run'
      # /opt/circleci/.rvm/gems/ruby-2.1.8/gems/factory_girl-4.8.0/lib/factory_girl/factory_runner.rb:29:in `block in run'
      # /opt/circleci/.rvm/gems/ruby-2.1.8/gems/activesupport-4.2.8/lib/active_support/notifications.rb:166:in `instrument'
      # /opt/circleci/.rvm/gems/ruby-2.1.8/gems/factory_girl-4.8.0/lib/factory_girl/factory_runner.rb:28:in `run'
      # /opt/circleci/.rvm/gems/ruby-2.1.8/gems/factory_girl-4.8.0/lib/factory_girl/strategy/create.rb:5:in `association'
      # /opt/circleci/.rvm/gems/ruby-2.1.8/gems/factory_girl-4.8.0/lib/factory_girl/evaluator.rb:33:in `association'
      # /opt/circleci/.rvm/gems/ruby-2.1.8/gems/factory_girl-4.8.0/lib/factory_girl/attribute/association.rb:19:in `block in to_proc'
      # /opt/circleci/.rvm/gems/ruby-2.1.8/gems/factory_girl-4.8.0/lib/factory_girl/evaluator.rb:77:in `instance_exec'
      # /opt/circleci/.rvm/gems/ruby-2.1.8/gems/factory_girl-4.8.0/lib/factory_girl/evaluator.rb:77:in `block in define_attribute'
      # /opt/circleci/.rvm/gems/ruby-2.1.8/gems/factory_girl-4.8.0/lib/factory_girl/attribute_assigner.rb:56:in `get'
      # /opt/circleci/.rvm/gems/ruby-2.1.8/gems/factory_girl-4.8.0/lib/factory_girl/attribute_assigner.rb:16:in `block (2 levels) in object'
      # /opt/circleci/.rvm/gems/ruby-2.1.8/gems/factory_girl-4.8.0/lib/factory_girl/attribute_assigner.rb:15:in `each'
      # /opt/circleci/.rvm/gems/ruby-2.1.8/gems/factory_girl-4.8.0/lib/factory_girl/attribute_assigner.rb:15:in `block in object'
      # /opt/circleci/.rvm/gems/ruby-2.1.8/gems/factory_girl-4.8.0/lib/factory_girl/attribute_assigner.rb:14:in `tap'
      # /opt/circleci/.rvm/gems/ruby-2.1.8/gems/factory_girl-4.8.0/lib/factory_girl/attribute_assigner.rb:14:in `object'
      # /opt/circleci/.rvm/gems/ruby-2.1.8/gems/factory_girl-4.8.0/lib/factory_girl/evaluation.rb:12:in `object'
      # /opt/circleci/.rvm/gems/ruby-2.1.8/gems/factory_girl-4.8.0/lib/factory_girl/strategy/create.rb:9:in `result'
      # /opt/circleci/.rvm/gems/ruby-2.1.8/gems/factory_girl-4.8.0/lib/factory_girl/factory.rb:42:in `run'
      # /opt/circleci/.rvm/gems/ruby-2.1.8/gems/factory_girl-4.8.0/lib/factory_girl/factory_runner.rb:29:in `block in run'
      # /opt/circleci/.rvm/gems/ruby-2.1.8/gems/activesupport-4.2.8/lib/active_support/notifications.rb:166:in `instrument'
      # /opt/circleci/.rvm/gems/ruby-2.1.8/gems/factory_girl-4.8.0/lib/factory_girl/factory_runner.rb:28:in `run'
      # /opt/circleci/.rvm/gems/ruby-2.1.8/gems/factory_girl-4.8.0/lib/factory_girl/strategy_syntax_method_registrar.rb:20:in `block in define_singular_strategy_method'
      # ./spec/models/user_spec.rb:581:in `block (3 levels) in <top (required)>'
```

Offending line in `user_spec.rb`:

```ruby
let!(:listing_2) { FactoryGirl.create(:listing) }
```

`spec/factories/listings.rb`:

```ruby
FactoryGirl.define do
  factory :listing do
    association :category
    association :seller, factory: :user

    age { [3, 3, 9, 9, 10].sample }
    album_art_url { media.present? ? "http://example.com/images/#{rand(1000)}.png" : nil }
    album_art_back_url { media.present? ? "http://example.com/images/#{rand(1000)}-back.png" : nil }
    auction_opening_bid { Forgery(:monetary).formatted_money }
    auction_reserve_price { Forgery(:monetary).formatted_money }
    bold { (rand(2) == 0) }
    box_count 1
    brand { Forgery(:name).company_name }
    classified_asking_price_dollars { Forgery(:monetary).formatted_money(min: 1) }
    condition { rand(10) + 1 }
    description { Forgery(:lorem_ipsum).sentences(20) }
    hit_count { Forgery(:basic).number(at_most: 69) }
    media false
    product_name { Forgery(:basic).text }
    no_transaction_fee false
    payment_methods ["PERS", "DISC"]
    retail_price_dollars { Forgery(:monetary).formatted_money }
    ship_from "29601"
    ship_to "US"
    shipping_methods ["UPS", "FDX"]
    status Listing::STATUSES[:active]
    title { Forgery(:basic).text }
    auction_duration 7
  end

  factory :listing_with_shipping_info, parent: :listing do
    after(:create) do |listing|
      address = FactoryGirl.create(:address, user: listing.seller)
      listing.shipment.update_attributes(seller_address: address)
    end
  end
end
```

**Comment by Oshuma** [comment]
This ended up being an issue with our application code.  We had a `Category` model that had a `#parent_name` field, as well as a `Category.parent_name(child = nil)` class method that was conflicting with Rails core ext. `Module#parent_name()`.
